services:
  aqara-g5pro-mqtt:
    build: .
    container_name: aqara-g5pro-mqtt
    restart: unless-stopped
    env_file: ./app/.env
    environment:
      - NODE_ENV=production
    network_mode: host