services:
  aqara-g5pro-mqtt:
    image: ghcr.io/resonaura/aqara-g5pro-mqtt:latest
    # Or build locally:
    # build: .
    container_name: aqara-g5pro-mqtt
    restart: unless-stopped
    env_file: ./app/.env
    environment:
      - NODE_ENV=production
    network_mode: host