/**
 * generate_go2rtc.ts
 *
 * Emits a ready-to-use `go2rtc.yaml` that points go2rtc (and therefore
 * WebRTC / Home Assistant / Frigate / Scrypted) straight at the local P2P
 * RTSP streams produced by this bridge. This is the "Native WebRTC / go2rtc
 * Direct Integration" deliverable from REPORT4 §8.3.
 *
 * Usage:
 *   tsx src/scripts/generate_go2rtc.ts
 *   tsx src/scripts/generate_go2rtc.ts --out ./go2rtc.yaml --host 192.168.5.191
 *
 * Camera list is taken from `data/cameras.json` (array of {did,name,model}),
 * falling back to the CAMERAS env var ("did:Name;did2:Name2") and finally to
 * the already-cached offline session files in `data/keys_*.json`.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { slugifyStreamName } from "../../bridge.js";
import { findFreePortRange, readRtspPortMap } from "../../ports.js";
import { assignUniqueSlugs } from "../../slug.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..", "..");

interface Cam { did: string; name: string; model?: string }
interface CamPort { did: string; name: string; port: number; slug: string }

function parseArgs(argv: string[]) {
  let out = path.join(root, "go2rtc.yaml");
  let host = process.env.BRIDGE_HOST || process.env.BRIDGE_IP || "127.0.0.1";
  let portBase = parseInt(process.env.RTSP_PORT || "8555", 10);
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--out") out = argv[++i];
    else if (argv[i] === "--host") host = argv[++i];
    else if (argv[i] === "--port") portBase = parseInt(argv[++i], 10);
  }
  return { out, host, portBase };
}

function loadCameras(): Cam[] {
  const jsonPath = path.join(root, "data", "cameras.json");
  if (fs.existsSync(jsonPath)) {
    try { return JSON.parse(fs.readFileSync(jsonPath, "utf-8")); } catch {}
  }
  if (process.env.CAMERAS) {
    return process.env.CAMERAS.split(";").map((s) => {
      const [did, name] = s.split(":");
      return { did, name: name || did };
    }).filter((c) => c.did);
  }
  // Fall back to cached offline session files
  const dataDir = path.join(root, "data");
  const cams: Cam[] = [];
  if (fs.existsSync(dataDir)) {
    for (const f of fs.readdirSync(dataDir)) {
      if (f.startsWith("keys_") && f.endsWith(".json")) {
        try {
          const c = JSON.parse(fs.readFileSync(path.join(dataDir, f), "utf-8"));
          if (c.did) cams.push({ did: c.did, name: c.did });
        } catch {}
      }
    }
  }
  return cams;
}

async function main() {
  const { out, host, portBase } = parseArgs(process.argv.slice(2));
  const cams = loadCameras();

  // Prefer the actual ports the bridge chose at runtime (data/rtsp_ports.json);
  // fall back to computing a free contiguous block when that file is absent.
  const map = readRtspPortMap();
  const useMap = map && cams.length > 0 && cams.every((c) => map.cameras[c.did]);
  const rawPorts: CamPort[] = [];
  if (useMap && map) {
    for (const c of cams) {
      const e = map.cameras[c.did];
      rawPorts.push({ did: c.did, name: c.name, port: e.port, slug: e.slug });
    }
  } else {
    const ports = findFreePortRange(cams.length, portBase);
    cams.forEach((c, i) => {
      const s = slugifyStreamName(c.name || c.did);
      rawPorts.push({ did: c.did, name: c.name, port: ports[i], slug: s });
    });
  }

  // De-duplicate slugs across cameras (collision handling).
  const slugMap = assignUniqueSlugs(rawPorts.map((c) => ({ did: c.did, name: c.name })));
  const camPorts: CamPort[] = rawPorts.map((c) => ({ ...c, slug: slugMap[c.did] }));

  const lines: string[] = [];
  lines.push("# Auto-generated by aqara-g5pro-mqtt generate_go2rtc.ts");
  lines.push("# Point Home Assistant / Frigate / Scrypted at these WebRTC streams.");
  lines.push("go2rtc:");
  lines.push("  streams:");

  camPorts.forEach((cam) => {
    const url = `rtsp://${host}:${cam.port}/live/${cam.slug}`;
    lines.push(`    ${cam.slug}:`);
    lines.push(`      - ${url}`);
    // WebRTC wants a single muxed track; go2rtc handles PCMA audio natively.
    lines.push(`    ${cam.slug}_webrtc:`);
    lines.push(`      - ${url}`);
    lines.push(`      - ffmpeg:${cam.slug}#audio=opus`);
  });

  if (camPorts.length === 0) {
    lines.push("    # No cameras discovered yet. Start the bridge (npm start) to");
    lines.push("    # populate data/keys_*.json, then re-run this generator.");
  }

  lines.push("");
  lines.push("webrtc:");
  lines.push("  listen: \":1984\"");
  lines.push("");

  fs.writeFileSync(out, lines.join("\n"));
  console.log(`✅ Wrote go2rtc config -> ${out}`);
  console.log(`   Streams: ${camPorts.map((c) => c.slug).join(", ") || "(none)"}`);
  if (camPorts.length) {
    console.log(`   Example WebRTC URL: rtsp://${host}:1984/${camPorts[0].slug}_webrtc`);
  }
}

main();
