import { EntityConfig } from "./types.js";

export const ENTITIES: EntityConfig[] = [
  {
    domain: "switch",
    name: "Lens Obstruction Detection",
    attr: "lens_hide_enable",
    command: true,
    icon: "mdi:camera-off",
  },
  {
    domain: "switch",
    name: "AI Sound Detection",
    attr: "ai_sound_enable",
    icon: "mdi:microphone",
    command: true,
  },
  {
    domain: "switch",
    name: "Face Detection",
    attr: "face_detect_enable",
    icon: "mdi:face-recognition",
    command: true,
  },
  {
    domain: "switch",
    name: "Human Detection",
    attr: "human_detect_enable",
    icon: "mdi:walk",
    command: true,
  },
  {
    domain: "switch",
    name: "Pets Detection",
    attr: "pets_detect_enable",
    icon: "mdi:paw",
    command: true,
  },
  {
    domain: "switch",
    name: "Vehicle Detection",
    attr: "vehicle_detect_enable",
    icon: "mdi:car",
    command: true,
  },
  {
    domain: "switch",
    name: "Package Detection",
    attr: "package_detect_enable",
    icon: "mdi:package-variant",
    command: true,
  },
  {
    domain: "switch",
    name: "Lingerer Detection",
    attr: "pir_enable",
    icon: "mdi:motion-sensor",
    command: true,
  },
  {
    domain: "number",
    name: "System Volume",
    attr: "system_volume",
    icon: "mdi:volume-high",
    command: true,
    unit: "%",
  },
  {
    domain: "number",
    name: "Alarm Volume",
    attr: "alarm_bell_volume",
    icon: "mdi:alarm-bell",
    command: true,
    unit: "%",
  },
  {
    domain: "number",
    name: "Alarm Tone",
    attr: "alarm_bell_index",
    icon: "mdi:bell",
    command: true,
  },
  {
    domain: "number",
    name: "Report Interval",
    attr: "report_status_sec",
    icon: "mdi:timer",
    command: true,
    unit: "s",
  },
  {
    domain: "sensor",
    name: "WiFi RSSI",
    attr: "device_wifi_rssi",
    icon: "mdi:wifi",
    unit: "dBm",
  },
  {
    domain: "sensor",
    name: "WiFi Level",
    attr: "wifi_level",
    icon: "mdi:wifi",
  },
  {
    domain: "sensor",
    name: "SD Card",
    attr: "sdcard_status",
    icon: "mdi:sd-card",
  },
  {
    domain: "sensor",
    name: "Alarm Status",
    attr: "alarm_status",
    icon: "mdi:alarm",
  },

  {
    domain: "sensor",
    name: "P2P Stream",
    attr: "P2P_capture_status",
    icon: "mdi:camera",
  },
];
